name: Run UI Tests

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment To Test Against'
        type: choice
        default: dev
        options:
          - dev
          - stage

jobs:
  build:
    runs-on: [ ubuntu-latest ]
    environment: ${{ inputs.environment }}
    steps:
      - name: Run Test
        env:
          SECRET1: ${{ secrets.SECRET1 }}
          SECRET2: ${{ secrets.SECRET3 }}
          SECRET3: ${{ secrets.SECRET3 }}
        run: docker run alpine:latest env | sort
              